AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tech-crawler

  Sample SAM Template for tech-crawler

Globals:
  Function:
    Timeout: 3

Resources:
  TechCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tech_crawler/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        TechCrawlerSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Enabled: True


Outputs:
  TechCrawlerFunction:
    Description: "Tech Crawler Lambda Function ARN"
    Value: !GetAtt TechCrawlerFunction.Arn
  TechCrawlerFunctionIamRole:
    Description: "Implicit IAM Role created for Tech Crawler function"
    Value: !GetAtt TechCrawlerFunctionRole.Arn
